In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sns

In [2]:
drug_data = pd.read_csv("C:/Users/Rui Wu/Documents/Programming C Drive/Final Project/cleaned_drug_new.csv")
drug_data.shape

(1885, 20)

In [3]:
drug_data_y = drug_data['Illicit Drugs']
drug_data_x = drug_data.drop(['Illicit Drugs', 'ID'], axis = 1)
drug_data_x = drug_data_x.astype('category')

drug_dummies = pd.get_dummies(drug_data_x[drug_data_x.columns])
drug_dummies.head()

Age_-0.9519700000000001  Age_-0.07854  Age_0.49788000000000004  \
0                        0             0                        1   
1                        0             1                        0   
2                        0             0                        1   
3                        1             0                        0   
4                        0             0                        1   

   Age_1.09449  Age_1.82213  Age_2.59171  Gender_Female  Gender_Male  \
0            0            0            0              1            0   
1            0            0            0              0            1   
2            0            0            0              0            1   
3            0            0            0              1            0   
4            0            0            0              1            0   

   Education_-2.43591  Education_-1.7379  ...  Legal High_CL4  Legal High_CL5  \
0                   0                  0  ...               0               0   
1                   0                  0  ...               0               0   
2                   0                  0  ...               0               0   
3                   0                  0  ...               0               0   
4                   0                  0  ...               0               0   

   Legal High_CL6  Nicotine_CL0  Nicotine_CL1  Nicotine_CL2  Nicotine_CL3  \
0               0             0             0             1             0   
1               0             0             0             0             0   
2               0             1             0             0             0   
3               0             0             0             1             0   
4               0             0             0             1             0   

   Nicotine_CL4  Nicotine_CL5  Nicotine_CL6  
0             0             0             0  
1             1             0             0  
2             0             0             0  
3             0             0             0  
4             0             0             0  

[5 rows x 302 columns]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(drug_dummies, drug_data_y, test_size=0.2, random_state=0)

kf = KFold(n_splits=4, shuffle=True, random_state=0)
i = 0
scores = []
total_cm = [[0,0],[0,0]]
for train_index, test_index in kf.split(drug_dummies):
    i = i + 1
    print("Iteration " + str(i))
    x_train, x_test = drug_dummies.iloc[train_index], drug_dummies.iloc[test_index]
    y_train, y_test = drug_data_y.iloc[train_index], drug_data_y.iloc[test_index]
    
    logRegModel = LogisticRegression()
    logRegModel.fit(x_train, y_train)
    
    predictions = logRegModel.predict(x_test)
    score = logRegModel.score(x_test, y_test)
    scores.append(score)
    print("Accuracy is: " + str(score))
    
    cm = metrics.confusion_matrix(y_test, predictions)
    print(cm)
    
    for a in range(len(cm)):
        for b in range(len(cm)):
            total_cm[a][b] += cm[a][b]

print("True Negatives Rate: " + str(total_cm[0][0] / 1154))
print("True Positives Rate: " + str(total_cm[1][1] / 731))
print("False Negatives Rate: " + str(total_cm[1][0] / 731))
print("False Positives Rate: " + str(total_cm[0][1] / 1154))

scores_mean = sum(scores) / len(scores)
scores_std = np.std(np.array(scores))

print("Overall Accuracy: %0.4f (+/- %0.4f)" % (scores_mean, scores_std * 2))

Iteration 1
Accuracy is: 0.7838983050847458
[[237  58]
 [ 44 133]]
Iteration 2
Accuracy is: 0.7643312101910829
[[218  47]
 [ 64 142]]
Iteration 3
Accuracy is: 0.7813163481953291
[[245  53]
 [ 50 123]]
Iteration 4
Accuracy is: 0.7749469214437368
[[248  48]
 [ 58 117]]
True Negatives Rate: 0.8214904679376083
True Positives Rate: 0.7045143638850889
False Negatives Rate: 0.2954856361149111
False Positives Rate: 0.17850953206239167
[0.7838983050847458, 0.7643312101910829, 0.7813163481953291, 0.7749469214437368]
Overall Accuracy: 0.7761 (+/- 0.0151)


D:\Programming\Anaconda_Working\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Programming\Anaconda_Working\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Programming\Anaconda_Working\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Programming\Anaconda_Working\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
